default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless Apply
        entry: bash ./script/spotless-pre-commit
        language: system
        verbose: true
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
