spring:
  datasource:
    url: ${DB_URL:jdbc:tc:postgresql:15:///dev-db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      base-path: "/manage"
  endpoint:
    health:
      show-details: always
